"""
YOLOv8l-seg Instance Segmentation Training Pipeline for Rice Quality AI.

Real training code using Ultralytics YOLOv8 large segmentation model.
Supports:
- COCO pretrained initialization (auto-download)
- Fine-tune from existing best checkpoint
- CLI argument overrides
- Automatic hardware detection (CPU/GPU)
- OOM batch size fallback
- Structured run logging to training/run_log.md
"""

import argparse
import logging
import platform
import sys
import time
from datetime import datetime
from pathlib import Path
from typing import Dict, Optional

PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

try:
    from ultralytics import YOLO
except ImportError:
    logger.error("Ultralytics package is not installed.")
    logger.error("Install it with:  pip install ultralytics")
    logger.error("Then re-run this script.")
    sys.exit(1)


def detect_hardware() -> Dict:
    """Detect available hardware and return configuration recommendations."""
    info = {
        "gpu_available": False,
        "device_name": "CPU",
        "num_workers": 0 if platform.system() == "Windows" else 4,
    }

    try:
        import torch

        if torch.cuda.is_available():
            info["gpu_available"] = True
            info["device_name"] = torch.cuda.get_device_name(0)
            gpu_mem = torch.cuda.get_device_properties(0).total_memory / (1024 ** 3)
            if gpu_mem < 8:
                info["num_workers"] = 2
            elif platform.system() != "Windows":
                info["num_workers"] = 4
        else:
            info["device_name"] = platform.processor() or "CPU"
    except ImportError:
        info["device_name"] = platform.processor() or "CPU"

    return info


def get_existing_run_index(project_dir: Path) -> int:
    """Scan existing runs in project_dir and return the next run number N."""
    if not project_dir.exists():
        return 1

    max_idx = 0
    for child in project_dir.iterdir():
        if child.is_dir():
            name = child.name
            if name.startswith("run"):
                try:
                    idx_part = name.split("_")[0].replace("run", "")
                    idx = int(idx_part)
                    if idx > max_idx:
                        max_idx = idx
                except (ValueError, IndexError):
                    continue

    return max_idx + 1


def append_run_log(log_path: Path, run_data: Dict) -> None:
    """Append a structured run entry to run_log.md. Create file with header if missing."""
    log_path.parent.mkdir(parents=True, exist_ok=True)

    header = "# Rice Segmentation YOLO Training Run Log\n\n" \
             "Automatically generated by training/train_yolo_seg.py.\n\n"

    entry = (
        f"## Run {run_data['run_number']} - {run_data['date']}\n\n"
        f"- **Model:** yolov8l-seg\n"
        f"- **Dataset:** GrainSet v3 + synthetic\n"
        f"- **Epochs:** {run_data['total_epochs']} (early stop at epoch {run_data['best_epoch']})\n"
        f"- **Best val mAP@50:** {run_data['map50']}\n"
        f"- **Best val mAP@50:95:** {run_data['map50_95']}\n"
        f"- **Duration:** {run_data['duration_hours']} hours {run_data['duration_min']} min\n"
        f"- **Hardware:** {run_data['hardware']}\n"
        f"- **Notes:** {run_data['notes']}\n\n"
    )

    if not log_path.exists():
        with open(log_path, "w", encoding="utf-8") as f:
            f.write(header)
            f.write(entry)
    else:
        with open(log_path, "a", encoding="utf-8") as f:
            f.write(entry)

    logger.info(f"Run log appended to {log_path}")


def _resolve_weights(weights_arg: Optional[str], resume: bool,
                    project_dir: Path, baseline_name: str) -> str:
    """Resolve starting weights: resume or fine-tune from best.pt if available."""
    if weights_arg:
        return weights_arg

    if resume:
        best_pt = project_dir / baseline_name / "weights" / "best.pt"
        if best_pt.exists():
            logger.info(f"--resume set: using existing best weights at {best_pt}")
            return str(best_pt)
        else:
            logger.warning(f"--resume set but no checkpoint at {best_pt}, falling back to COCO pretrained")
            return "yolov8l-seg.pt"

    best_pt = project_dir / baseline_name / "weights" / "best.pt"
    if best_pt.exists():
        logger.info(f"Found existing best.pt at {best_pt} — fine-tune mode (Run 2+)")
        return str(best_pt)

    logger.info("No existing checkpoint found — starting from COCO pretrained yolov8l-seg.pt")
    return "yolov8l-seg.pt"


def train_with_fallback(model, train_kwargs: Dict, initial_batch: int) -> Dict:
    """Run model.train(); if OOM, halve batch and retry once."""
    try:
        return model.train(**train_kwargs)
    except RuntimeError as exc:
        msg = str(exc).lower()
        is_oom = ("out of memory" in msg or "oom" in msg or "cuda out of memory" in msg)
        if is_oom and initial_batch > 4:
            new_batch = initial_batch // 2
            logger.warning(f"OOM detected with batch={initial_batch}, retrying with batch={new_batch}")
            train_kwargs["batch"] = new_batch
            return model.train(**train_kwargs)
        raise


def main() -> None:
    parser = argparse.ArgumentParser(description="Train YOLOv8l-seg for rice grain segmentation")
    parser.add_argument("--weights", type=str, default=None,
                        help="Starting weights path (overrides auto detect/fine-tune logic)")
    parser.add_argument("--data", type=str, default="configs/rice_seg_yolo.yaml",
                        help="Path to dataset YAML config (relative to PROJECT_ROOT)")
    parser.add_argument("--epochs", type=int, default=100, help="Number of training epochs")
    parser.add_argument("--imgsz", type=int, default=640, help="Image size")
    parser.add_argument("--batch", type=int, default=16, help="Initial batch size")
    parser.add_argument("--name", type=str, default="run1_baseline",
                        help="Experiment name for output directory")
    parser.add_argument("--resume", action="store_true",
                        help="Resume / fine-tune from existing run1_baseline best.pt")
    parser.add_argument("--device", type=str, default=None,
                        help="Device: 'cpu', '0', '0,1', etc. (auto if omitted)")
    parser.add_argument("--lr0", type=float, default=0.001, help="Initial learning rate")
    parser.add_argument("--optimizer", type=str, default="AdamW",
                        choices=["SGD", "Adam", "AdamW", "RMSProp"],
                        help="Optimizer")
    parser.add_argument("--notes", type=str, default="",
                        help="Free-form notes appended to run log entry")
    args = parser.parse_args()

    hw = detect_hardware()
    logger.info(f"Hardware detected: GPU={hw['gpu_available']}, device={hw['device_name']}, "
                f"workers={hw['num_workers']}")

    project_dir = PROJECT_ROOT / "models" / "yolo_seg"
    data_config_path = PROJECT_ROOT / args.data

    if not data_config_path.exists():
        logger.error(f"Dataset config not found at {data_config_path}")
        sys.exit(1)

    weights_path = _resolve_weights(args.weights, args.resume, project_dir, args.name)
    logger.info(f"Starting weights: {weights_path}")

    device_str = args.device
    if device_str is None:
        device_str = "cuda" if hw["gpu_available"] else "cpu"

    run_idx = get_existing_run_index(project_dir)

    train_kwargs = dict(
        data=str(data_config_path),
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch,
        optimizer=args.optimizer,
        lr0=args.lr0,
        lrf=0.01,
        patience=20,
        save=True,
        save_period=10,
        project=str(project_dir),
        name=args.name,
        exist_ok=True,
        degrees=45.0,
        flipud=0.5,
        fliplr=0.5,
        mosaic=1.0,
        copy_paste=0.3,
        mixup=0.1,
        hsv_h=0.015,
        hsv_s=0.7,
        hsv_v=0.4,
        device=device_str,
        workers=hw["num_workers"],
        verbose=True,
    )

    logger.info("Initializing YOLOv8l-seg model...")
    model = YOLO(weights_path)

    start_time = time.time()
    logger.info("Starting training...")
    results = train_with_fallback(model, train_kwargs, args.batch)
    duration_sec = time.time() - start_time

    dur_h = int(duration_sec // 3600)
    dur_m = int((duration_sec % 3600) // 60)

    try:
        best_map50 = results.results_dict.get("metrics/mAP50(M)", None)
        best_map50_95 = results.results_dict.get("metrics/mAP50-95(M)", None)
    except Exception:
        best_map50 = None
        best_map50_95 = None

    best_epoch = 0
    try:
        if hasattr(results, "best_fitness") and hasattr(model.trainer, "best_epoch"):
            best_epoch = model.trainer.best_epoch
        elif hasattr(model, "trainer") and hasattr(model.trainer, "best_epoch"):
            best_epoch = model.trainer.best_epoch
    except Exception:
        best_epoch = 0

    if best_epoch == 0:
        best_epoch = args.epochs

    best_map50_str = f"{best_map50:.4f}" if isinstance(best_map50, (int, float)) else "N/A"
    best_map50_95_str = f"{best_map50_95:.4f}" if isinstance(best_map50_95, (int, float)) else "N/A"

    logger.info("=" * 60)
    logger.info("TRAINING SUMMARY")
    logger.info("=" * 60)
    logger.info(f"Best val mAP@50:     {best_map50_str}")
    logger.info(f"Best val mAP@50:95:  {best_map50_95_str}")
    logger.info(f"Best epoch:          {best_epoch}")
    logger.info(f"Total epochs:        {args.epochs}")
    logger.info(f"Training duration:   {dur_h}h {dur_m}m")
    logger.info(f"Output directory:    {project_dir / args.name}")
    logger.info("=" * 60)

    log_path = PROJECT_ROOT / "training" / "run_log.md"
    run_data = {
        "run_number": run_idx,
        "date": datetime.now().strftime("%Y-%m-%d %H:%M"),
        "total_epochs": args.epochs,
        "best_epoch": best_epoch,
        "map50": best_map50_str,
        "map50_95": best_map50_95_str,
        "duration_hours": dur_h,
        "duration_min": dur_m,
        "hardware": hw["device_name"] + (" (GPU)" if hw["gpu_available"] else " (CPU)"),
        "notes": args.notes or "Baseline run with COCO pretrained init." if run_idx == 1 else args.notes,
    }
    append_run_log(log_path, run_data)


if __name__ == "__main__":
    main()
